# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  send-html-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Read index.html content
      id: read-file
      run: |
        content=`cat index.html`
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=content::$content"

    - name: POST the content
      run: |
        curl -X POST -H "Content-Type: text/plain" --data "${{ steps.read-file.outputs.content }}" https://jbcharging.com/update-html
