# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update HTML
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" https://jbcharging.com/update-html

      - name: Update CSS
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" https://jbcharging.com/update-css

      - name: Update JavaScript
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" https://jbcharging.com/update-js
